### ISSUE TITLE
Testing strategy for release

### ISSUE THREAD

**Issue by heyjerrybecker** [openpracticelibrary/opl-docs#119]
As a product manager, I need a way to gauge user feedback on the new OPL web app experience during the canary release period and post-full rollout so I can maximize the value to users based on an understanding of their wants and needs.

**NOTES**
- Document the release and test plan
- How using Loop11 / Why / When 
- Combine with Qualitative
- A/B Test
- Custom Google Analytics for Jul 3?

- [App Testing Strategy](https://docs.google.com/document/d/1UbAOVL6iqDYS1Nl8MntmdH0Mg0AOgSEUSXFcey_hZQg/edit#)

**Comment by DarcieF** [comment]
### User Feedback Strategy: 
- Barebones track with Google Analytics
- Possibly create custom tracking
- User form for giving feedback 
- Design Notes: Send us feedback Form / is left nav a good location

### Automated Testing Strategy: 
- E2E framework in place
- High priority user flows are tested 
- eg. I want to see Event Storming, how do I get there? 
- 1) type url and go directly to practice page
- 2) navigate to the practice page through landing page 
- 3) navigate to all practices and use filters to surface practice then go to practice page
- eg. I need to add an image to the Event Storming practice page, how to I get there and contribute that asset?
- Focus on Nova for priorities of testing
- Consider using feature toggle

### Release + Documentation Strategy: 
- Get us to start releasing to product for v1 Jul 3
- Be transparent about where we are on the technical side and release cycles
- Focus on simplest user flows for automated testing for the soft launch to public which are Nova priorities
- Remove access to Landing Page for v1 Jul 3

### Action Item:
- @heyjerrybecker and @omcneil to create document for this plan

**Comment by omcneil** [comment]
https://docs.google.com/document/d/1UbAOVL6iqDYS1Nl8MntmdH0Mg0AOgSEUSXFcey_hZQg/edit#

**Comment by omcneil** [comment]
v3 testers identified
Google Form created

**Comment by lallmon** [comment]
Going to close this, as it has been released, but #57 is also relevant and possibly priority
