### ISSUE TITLE
Collaborative Document for v1 Marketing Copy

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-docs#123]
**NOTES**
- Creating a working Google Doc to determine page copy for v1 internal launch
- Sections of editable copy added here: https://docs.google.com/document/d/137wufcCfBHWDH9gdmpZV1NZ8Yuv7JaLNn5nZW02qRHE/edit?usp=sharing
- About page in separate doc: https://docs.google.com/document/d/1J6S6ykWR_iLTbwWLYhjWdYkQ4VwsmoafyMy7dlD9z2U/edit?usp=sharing
- Including design reference and Zeplin links as needed
- Have Brian Barringhausen (sp?) do copy editing

**Comment by omcneil** [comment]
Omar to follow up with Jana and Kari for review

**Comment by omcneil** [comment]
On Wed, Jun 24, 2020 at 1:50 PM Omar McNeil <omcneil@redhat.com> wrote:
Kari/Jana,
Here is the link to the doc - https://docs.google.com/document/d/137wufcCfBHWDH9gdmpZV1NZ8Yuv7JaLNn5nZW02qRHE/edit?usp=sharing

**Comment by omcneil** [comment]
On Thu, Jun 25, 2020 at 9:49 AM Omar McNeil <omcneil@redhat.com> wrote:
Morning Kari/Jana,
Following up from yesterday, have you had a chance to look over the doc, do you have any questions?

Also, the copyright person that was identified in our last call was Brian Barringhousing (spelling), is that correct?
