### ISSUE TITLE
About Page - First Pass on Content

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-docs#126]
**NOTES**
- Google document for copy drafting: https://docs.google.com/document/d/1J6S6ykWR_iLTbwWLYhjWdYkQ4VwsmoafyMy7dlD9z2U/edit?usp=sharing
- Design file for reference: https://zpl.io/a8g9QKE
- Collaborating as a team to draft this content
- Will share with Marketing to get opinions on words for SEO needs

**Comment by lallmon** [comment]
First Pass Done
