### ISSUE TITLE
Write OPL blog post

### ISSUE THREAD

**Issue by heyjerrybecker** [openpracticelibrary/opl-docs#141]
To do:
- Write a blog post for marketing that will go on Red Hat's blog and will serve as the centerpiece for the OPL marketing effort

**Comment by kattekrab** [comment]
@heyjerrybecker is this done? Is this this?
https://www.redhat.com/en/blog/open-practice-library-basics-starting-new-team

**Comment by kattekrab** [comment]
I'm going to yes, that was it, and close this out.

Since then, we've also done some webinars about OPL, and a post on contributing to opensource.com
