### ISSUE TITLE
Review & Analyze OPL Metrics 

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-docs#5]
As a PM, I need to review current OPL usage metrics to understand how the tool is being used by users today in order to inform what features and functionality should go into the next release.

NOTES: 
Look at the following metrics as a starting point to cross analyze with qualitative data. 

- best content
- newest content
- user journey
- bounce rate (trends?)
- other?

**Comment by omcneil** [comment]
Reviewed and shared with team
