### ISSUE TITLE
Schedule Usability Testing

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-docs#52]
As a Product team we need to email user research participants to schedule time for connecting for usability testing of MVP Concept.

**Comment by omcneil** [comment]
4 out of the 5 Users have been scheduled
![image](https://user-images.githubusercontent.com/48070845/82473417-862c2280-9a97-11ea-976c-269fa77cc545.png)

**Comment by omcneil** [comment]
Follow up email was sent to the 5th user:
On Wed, May 20, 2020 at 9:27 AM Jerry Becker <openpracticelibraryteam@gmail.com> wrote:
Greetings Carolyn,
We wanted to follow up with you to see if you are still available to meet us this week for usability testing.  If you are not available this week, please let us know and we will include you in the next round of testing.
Thank you so much,
Jerry Becker & Team
