### ISSUE TITLE
Logo Design Iterations - Next Steps

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-docs#66]
As a Product Manager I need to explore options and strategy for generating additional ideas for the new OPL logo design so that I can have a good amount of concepts to review.

NOTES: 
- Maybe look into hiring or paying for a service: 
- https://www.designcrowd.com/
- https://99designs.com/
- https://www.linkedin.com/profinder
- Submission: https://drive.google.com/open?id=1qOwK5ic_T8AwS-nwISj2gVSv4H3PA1Rc

Next steps:
- Review submissions and rate/select any for consideration going forward

**Comment by heyjerrybecker** [comment]
Ran logo design project through DesignCrowd and all ideas have been [uploaded to drive here](https://drive.google.com/open?id=1iMmQHggW6Zz5iRH323jIQL0D3YGEvKic)
