### ISSUE TITLE
Existing Data for Practice Content Needs to be Cleaned/Edited

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-docs#70]
As a Product team and OPL system, we need clean data for the launch of the MVP that aligns with the Practice Page template and other pages of the app so that the design team can create visual design and the assets meet the needs of Nova.

**NOTES**
- How many practices do we want to launch with? 
- Start with Top 8...
- Need image thumbnails that are not illustration and are an image of the practice in practice
- Need to curate/clean top content with the correct sections of the templates
- Does all top practices have all content sections complete? 
- Are Practice Titles accurate? 
- Are tag and Mobius categories accurate? 
- Does data align with data structure? 
- This starts with shared knowledge story https://github.com/openpracticelibrary/opl-docs/issues/73
- Curate (real life images) for thumbs - and images for Media Gallery and add here: https://drive.google.com/open?id=1QwVMlFl4Xc_rs3cOmdzgABBF46RkPXTj

**BLOCKERS**
- Can not work on visual design until some of this comes together
- Current data does not necessarily align with layout of new Practice Page template
- Need to also edit data for filters and additional features

**Comment by heyjerrybecker** [comment]
There's definitely some clean up to do, but I think we can move everything over and just put placeholders for content areas that aren't built out yet in existing writeups. That delivers the value to users of at least being exposed to all the practices we have, but also in a way that keeps the content page layout we've built the same from practice to practice. It might just mean we have cases where there's the header for, say, "How to do it" but there's no content within it
