### ISSUE TITLE
Shared Knowledge of Practice Data

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-docs#73]
As a Product Designer I need to align my designs with the existing data limits so that I account for functionality or UI that will address that.

**NOTES**
- Understanding structure for data on Practice Pages 
- Explore extremes of data types such as # of Contributors, # of Resources, # of media, etc.
- Learn and discover any unknowns not accounted for in current designs

**BLOCKERS**
- This will be crucial to help inform next iterations of static design to the Practice Page template
- This Spike will also inform a pairing session for Design and Frontend refinements

**Comment by omcneil** [comment]
Timebox = 2 hrs

**Comment by DarcieF** [comment]
Hey @jameshbarton adding some of my notes here from our pairing session: 

**Practice Page Template**
- Discussion about Contributors vs. Editors (will update designs to include look)
- May need rules for data structure 2 types for FE: 1) Author, Co-Author (max 2 people) 2) Contributors (or Editors need to validate naming)
- Reorganizing content layout based on user feedback / moving gallery to below (how to)
- Adding subsections to How To based on feedback: 1) Steps (required/validated user need) 2) Other (tbd)
- Creating further definition for Resources, validated four types: 1) Citation 2) Shopping List 3) Download File 4) Template Link 5) Some catch all (tbd) 
- NOTE: Podcast was somewhat confusing to one user in last testing, will keep for now but this is not meant to include any media type (may test on media as a type and could be podcast, video, etc.)
- Talked about encouraging video to be added to gallery instead of Resource
- Discussed ways to maybe toggle to see more resources per type
- Discussed requiring a shopping list be an amazon to a list not individual product links
- Would like to move forward with concept of having empty sections of content include note about 'add to this practice' messaging

**All Practices Page**
- Talked about the tagging system and how hashtags will be incorporated
- Would need some required / pre-selected tags for Mobius loop and Main Filters Bar 
- Discussed feedback from users about Activity Type filter and that changing to Practice Type which would include several such as: Retrospective, Icebreaker, Good for Remote, and others... (tbd) 
- Discussed that in order to ensure content can be filtered it has to be accurately tagged Mobis and Main Filters, there could be requirements and approvals check points for doing so
- Discussed user feedback about potentially filtering by Role on product team - this could be future goals or be in a catchall hashtag (tbd)

**Comment by jameshbarton** [comment]
This spike is complete.  Closing this out per @shaheinm .
