### ISSUE TITLE
v1 Home Page - Visual Design Exploration

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-docs#81]
As Designer I need to define a user experience that helps Nova gain trust and reliance upon the OPL and relays the Core Values of the library with the visual look & feel.

**NOTES**
- Access designs via Abstract
- Focus on look & feel of home 
- Keep reference to other pages for reference on fonts 
- Explore lo-fi sketches for OPL characters
- Look at patterns for backgrounds that are accessible

**Comment by maryshak1996** [comment]
hopefully this link to WIP docs works: https://share.goabstract.com/f35fe5fb-a2ea-407a-a981-ce621e526836
