### ISSUE TITLE
Limiting Upvotes: Shouldn't be Unlimited

### ISSUE THREAD

**Issue by DarcieF** [openpracticelibrary/opl-docs#95]
[Bug] Anonymous users can click LIKE multiple times, in multiple places.

Remove the ability to like on a PracticeCard and on the Practice Page Header.

Only on the Practice Page Bar

**Comment by shaheinm** [comment]
@heyjerrybecker @DarcieF The team needs more information to groom this appropriately.

- Is this a strategy to limit the number of times an individual user can like/upvote a practice?
  - If so, any such implementation will require a method of tracking users, and will require us to comply with GDPR. **User profiles cannot feasibly be implemented in v1**, but even using a cookie or something similar to track a user and prevent multiple clicks on the heart icon can be considered personal data.
